### ISSUE TITLE
Content moderation form on manage display breaks the confirmation page

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#236]
If its placed, you can't actually set the banner live on the confirmation screen.

_Originally posted by @andybroomfield in https://github.com/localgovdrupal/localgov_alert_banner/issues/174#issuecomment-1426916032_

**Comment by finnlewis** [comment]
@stephen-cox might have a fix! 😄

**Comment by stephen-cox** [comment]
I fixed this on a client site with the following

```patch
diff --git a/templates/localgov-alert-banner.html.twig b/templates/localgov-alert-banner.html.twig
index 4d7d38d..ba38ea6 100644
--- a/templates/localgov-alert-banner.html.twig
+++ b/templates/localgov-alert-banner.html.twig
@@ -46,7 +46,7 @@
         {% endif %}
 
         <div class="localgov-alert-banner__body">
-          {{ content|without('title', 'link') }}
+          {{ content|without('title', 'link', 'content_moderation_control') }}
         </div>
 
         {% if has_link %}
```

@andybroomfield suggests it's better to hide the content moderation controls in a preprocess hook

**Comment by andybroomfield** [comment]
Have verififed the problem is still present by adding the moderaction controls form onto an alert banner manage display and trying to make a banner live. The fix @stephen-cox suggests does work, although this does mean if an admin theme does modify the template or we use the main theme as a preview this issue could re-occur if the template does not include this fix.

There is also the possiblitlty that a site builder might want to include the moderation form on an alert banner for site admins.

I'm thinking a preprocess function that checks if we are on the confirmation page to address this.
